(("Features"
  "c-plus-plus"
  "comma-commands"
  "compiler-available"
  "disassemble"
  "five-to-six-to-seven"
  "implementation-language"
  "implementation-support"
  "jiffies-per-second"
  "load-path"
  "minischeme-history"
  "optionality"
  "scheme-on-windows"
  "standalone-executables")

 ("Macros"
  "macroexpand"
  "syntax-definitions"
  "self-referencial macro"
  "syntax-definitions-to-infinity-and-beyond"
  "syntax-mutation"
  "hygienic-macros")

 ("Bindings"
  "chez-repl-semantics"
  "define-syntax-defines"
  "empty-define"
  "eval-define"
  "fluid-let"
  "hygienic-inclusion"
  "letrec-star"
  "lisp-top-levels"
  "petrofsky-let"
  "redefining-keywords"
  "redefining-syntax"
  "redundant-imports"
  "set-syntax"
  "set-undefined-variable"
  "syntax-abuse")

 ("Evaluation"
  "apply-args-limit"
  "argument-order"
  "call-cc"
  "cond-expand"
  "empty-list"
  "eval-procedure"
  "force-non-promise"
  "guard-behavior"
  "multiple-values"
  "one-armed-if"
  "parameters-and-threads"
  "petrofsky-catastrophe"
  "self-quoting-vectors"
  "what-load-returns")

 ("Identity and mutability"
  "char-eq"
  "disjoint-promises"
  "empty-strings-vectors"
  "exception-taxonomies"
  "immediate-strings-coalesced"
  "immutable-literals"
  "immutable-strings"
  "make-list-default-element"
  "nil-is-false"
  "read-mutable"
  "void-value")

 ("Lexical syntax"
  "backslash-bar"
  "brackets-braces"
  "case-insensitivity"
  "comma-in-identifiers"
  "datum-labels"
  "dot-comma"
  "empty-symbol-concatenated"
  "hash-bang-eof"
  "hash-in-identifiers"
  "hash-quote"
  "keyword-syntax"
  "one-plus-ex"
  "quote-delimiter"
  "reader-vertical-bar-concatenated-with-number"
  "square-brackets"
  "string-symbol-conversion"
  "unsigned-imaginary"
  "upper-case-escape"
  "vertical-line-symbols")

 ("Pairs and lists"
  "improper-lists"
  "property-lists")

 ("I/O and character encoding"
  "cwif-close-port"
  "embedded-cr-lf"
  "get-from-closed-string-port"
  "json-representations"
  "read-line"
  "readtables"
  "string-titlecase"
  "unicode-lambda"
  "unicode-support")

 ("Numbers"
  "complex-logarithm"
  "complex-representations"
  "exact-expt"
  "exact-sqrt"
  "fixnum-info"
  "float-precision"
  "max-inf-nan"
  "negative-rationalize"
  "negative-sqrt"
  "non-finite-numbers"
  "numeric-tower"
  "prefixed-string-to-number"
  "round-inf"
  "short-equality"
  "zero"))
